print(r'  ___  ___  ___')
print(r'  | |__| |__| |')
print(r'  |           |')
print(r'   \_________/')
print(r'    \_______/')
print(r'     |     |')
print(r'     |     |')
print(r'     |     |')
print(r'     |     |')
print(r'     |_____|')
print(r'  __/       \__')
print(' /             \\')
print('/_______________\\')
